name: 'ZLint Action'
description: 'Lint your Zig code with ZLint'
author: Don Isaac
branding:
  icon: zap
  color: yellow
  

inputs:
  version:
    description: Version of ZLint to use.
    required: true
    default: 'latest'
  binary:
    description: Use a pre-built ZLint binary. Overrides version.
    required: false

runs:
  using: 'node20'
  main: 'dist/index.js'
